// Generated by CoffeeScript 1.7.1
(function() {
  var ObjectId, dbHelper, mongodb, mongojs;

  dbHelper = require('../helper/dbHelper');

  mongodb = dbHelper.newDb();

  mongojs = require('mongojs');

  ObjectId = mongojs.ObjectId;


  /*
      添加问题
      info:
          title
          content
          viewNum
          resNum
          addTime
          updateTime
   */

  exports.add = function(info, cb) {
    return dbHelper.connectDB("questions", cb, function(collection) {
      return collection.insert(info, {
        safe: true
      }, function(err, question) {
        mongodb.close();
        if (err) {
          return cb(err);
        } else {
          return cb(null, question);
        }
      });
    });
  };


  /*
      查找单个问题
      id
   */

  exports.single = function(id, cb) {
    return dbHelper.connectDB("questions", cb, function(collection) {
      return collection.findOne({
        _id: ObjectId(id)
      }, function(err, question) {
        mongodb.close();
        if (err) {
          return cb(new Error(err));
        } else {
          return cb(null, question);
        }
      });
    });
  };


  /*
      获取所有问题
   */

  exports.all = function(cb) {
    return dbHelper.connectDB("questions", cb, function(collection) {
      return collection.find().sort({
        addTime: -1
      }).limit(10).toArray(function(err, items) {
        mongodb.close();
        if (err) {
          return cb(new Error(err));
        } else {
          return cb(null, items);
        }
      });
    });
  };

}).call(this);

//# sourceMappingURL=dbQuestion.map
