// Generated by CoffeeScript 1.8.0
(function() {
  var config, dataTimeHelper, fs, logHelper, path;

  fs = require("fs");

  path = require("path");

  config = require("../config");

  dataTimeHelper = require("../helper/dateTimeHelper");

  logHelper = require("../helper/logHelper");


  /*
    获取邮件发送日志
   */

  exports.index = function(req, res) {
    var filePath;
    filePath = path.join(__dirname, config.logPath.emailLog, dataTimeHelper.currentDate() + ".log");
    return fs.readFile(filePath, 'utf8', function(err, data) {
      if (err) {
        return logHelper.errorLog(err);
      } else {
        return res.send(data);
      }
    });
  };

}).call(this);

//# sourceMappingURL=email.js.map
