// Generated by CoffeeScript 1.8.0
(function() {
  var moment, questionBll, userBll, userHelper;

  questionBll = require("../Bll/questionBll");

  userHelper = require("../helper/userHelper");

  userBll = require("../Bll/userBll");

  moment = require("moment");

  moment.lang("zh-cn");


  /*
      index
      /explore
   */

  exports.index = function(req, res) {
    return questionBll.all(function(err, items) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        items.map(function(item) {
          item.addTime = moment(item.addTime).fromNow();
          return item.updateTime = moment(item.updateTime).fromNow();
        });
        return userBll.getAllUser(function(err, users) {
          if (err) {
            return res.send({
              code: 1,
              message: err.message
            });
          } else {
            return res.render("index", {
              loopExplore: true,
              items: items,
              users: users,
              isLogin: userHelper.isLogin(req, res)
            });
          }
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=explore.js.map
