// Generated by CoffeeScript 1.8.0
(function() {
  var questionBll;

  questionBll = require("../Bll/questionBll");


  /*
      index
      /explore
   */

  exports.index = function(req, res) {
    return questionBll.all(function(err, items) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return res.render("index", {
          loopExplore: true,
          items: items
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=explore.js.map
