<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0
=======
// Generated by CoffeeScript 1.7.1
>>>>>>> origin/master

/*
  index page
  localhost:8080
 */

(function() {
  exports.index = function(req, res) {
    return res.render("index");
  };


  /*
    home page
    localhost:8080/home
   */

  exports.all = function(req, res) {
    return res.render('home');
  };

}).call(this);

//# sourceMappingURL=home.map
