// Generated by CoffeeScript 1.8.0
(function() {
  var moment, questionBll, userBll, userHelper;

  questionBll = require("../Bll/questionBll");

  userBll = require("../Bll/userBll");

  userHelper = require("../helper/userHelper");

  moment = require("moment");

  moment.lang("zh-cn");


  /*
  mvc配置
  @type {{}}
   */

  exports.$mvcConfig = {
    route: {
      single: {
        path: "/single/:id",
        httpVerbs: ["get"]
      }
    }
  };


  /*
      添加问题
   */

  exports.add_POST = function(req, res) {
    var info;
    info = {
      title: req.body.title,
      content: req.body.content,
      user: {
        id: req.session.userId || 0,
        email: req.session.userEmail || '',
        name: req.session.userName || '游客',
        avatar: req.session.userAvatar || 'http://img.mukewang.com/user/53b6219500010ef010001000-40-40.jpg'
      }
    };
    return questionBll.add(info, function(err, question) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return res.redirect('/single/' + question[0]._id.toString());
      }
    });
  };


  /*
      获取单个问题
      id
   */

  exports.single = function(req, res) {
    var id;
    id = req.params.id;
    return questionBll.single(id, function(err, question) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        question.addTime = moment(question.addTime).fromNow();
        question.updateTime = moment(question.updateTime).fromNow();
        return questionBll.all(function(err, items) {
          if (err) {
            return res.send({
              code: 1,
              message: err.message
            });
          } else {
            items.map(function(item) {
              item.addTime = moment(item.addTime).fromNow();
              return item.updateTime = moment(item.updateTime).fromNow();
            });
            return userBll.getAllUser(function(err, users) {
              if (err) {
                return res.send({
                  code: 1,
                  message: err.message
                });
              } else {
                return res.render("single1", {
                  question: question,
                  items: items,
                  users: users,
                  isLogin: userHelper.isLogin(req, res)
                });
              }
            });
          }
        });
      }
    });
  };


  /*
      获取所有问题
   */

  exports.all = function(req, res) {
    return questionBll.all(function(err, items) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return res.send({
          code: 0,
          items: items
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=question.js.map
