// Generated by CoffeeScript 1.7.1
(function() {
  var questionBll;

  questionBll = require("../Bll/questionBll");


  /*
  mvc配置
  @type {{}}
   */

  exports.$mvcConfig = {
    route: {
      single: {
        path: "/single/:id",
        httpVerbs: ["get"]
      }
    }
  };


  /*
      添加问题
   */

  exports.add_POST = function(req, res) {
    var info;
    info = {
      title: req.body.title,
      content: req.body.content,
      userId: 0
    };
    return questionBll.add(info, function(err, question) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return res.redirect('/single/' + question[0]._id.toString());
      }
    });
  };


  /*
      获取单个问题
      id
   */

  exports.single = function(req, res) {
    var id;
    id = req.params.id;
    return questionBll.single(id, function(err, question) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return questionBll.all(function(err, items) {
          if (err) {
            return res.send({
              code: 1,
              message: err.message
            });
          } else {
            return res.render("single", {
              question: question,
              items: items
            });
          }
        });
      }
    });
  };


  /*
      获取所有问题
   */

  exports.all = function(req, res) {
    return questionBll.all(function(err, items) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return res.send({
          code: 0,
          items: items
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=question.map
