// Generated by CoffeeScript 1.8.0
(function() {
  var commentsBll, moment, questionBll, setSession, transTime, userBll, userHelper;

  questionBll = require("../Bll/questionBll");

  userHelper = require("../helper/userHelper");

  userBll = require("../Bll/userBll");

  commentsBll = require("../Bll/commentsBll");

  moment = require("moment");

  moment.lang("zh-cn");


  /*
  mvc配置
  @type {{}}
   */

  exports.$mvcConfig = {
    route: {
      index: {
        path: "/user/:id",
        httpVerbs: ["get"]
      }
    }
  };


  /*
      注册
      @param email
      @param password
   */

  exports.register_GET_POST = function(req, res) {
    var loc, user;
    loc = parseInt(Math.random() * 100) % 10;
    if (req.method === "POST") {
      user = {
        name: req.body.name,
        email: req.body.email,
        password: req.body.password,
        resNum: 0,
        ansNum: 0,
        avatar: "/images/avatar-big/default" + loc + ".jpg",
        score: 0
      };
      return userBll.register(user, function(err, result) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else {
          setSession(req, result[0]);
          return res.redirect('/explore');
        }
      });
    } else {
      return res.render("register", {
        isLogin: true
      });
    }
  };


  /*
      登录
      @param email
      @param password
   */

  exports.login_GET_POST = function(req, res) {
    var user;
    if (req.method === "POST") {
      user = {
        email: req.body.userName,
        password: req.body.pwd
      };
      return userBll.login(user, function(err, result) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else if (!result) {
          return res.send({
            code: 1,
            message: '用户不存在,请注册后登录'
          });
        } else {
          setSession(req, result);
          return res.send({
            code: 0,
            message: 'ok',
            result: result
          });
        }
      });
    }
  };


  /*获取用户信息
      退出登录
   */

  exports.signOut = function(req, res) {
    res.session.clear();
    return res.redirect("/explore");
  };


  /*
  	获取用户信息
   */

  exports.getUserInfo = function(req, res) {
    var userId;
    userId = req.query.id || req.session.userId;
    return userBll.getUserInfo(userId, function(err, user) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return res.send({
          code: 0,
          message: "ok",
          user: user
        });
      }
    });
  };


  /*
  	用户主页
   */

  exports.index = function(req, res) {
    var id;
    id = req.params.id;
    return userBll.getUserInfo(id, function(err, user) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return questionBll.getQuestionByUser(id, function(err, questions) {
          if (err) {
            return res.send({
              code: 1,
              message: err.message
            });
          } else {
            transTime(questions);
            return commentsBll.getCommentByUser(id, function(err, ansQuestions) {
              if (err) {
                return res.send({
                  code: 1,
                  message: err.message
                });
              } else {
                transTime(ansQuestions);
                return res.render("index", {
                  questions: questions,
                  ansQuestions: ansQuestions,
                  user: user,
                  isLogin: userHelper.isLogin(req, res)
                });
              }
            });
          }
        });
      }
    });
  };


  /*
  	转换时间
   */

  transTime = function(obj) {
    return obj.map(function(item) {
      item.addTime = moment(item.addTime).fromNow();
      return item.updateTime = moment(item.updateTime).fromNow();
    });
  };


  /*
      创建session
   */

  setSession = function(req, result) {
    req.session.userId = result._id.toString();
    req.session.userName = result.name;
    req.session.userEmail = result.email;
    return req.session.userAvatar = result.avatar;
  };

}).call(this);

//# sourceMappingURL=user.js.map
