// Generated by CoffeeScript 1.8.0
(function() {
  var userBll;

  userBll = require("../Bll/userBll");


  /*
      注册
      @param email
      @param password
   */

  exports.register_GET_POST = function(req, res) {
    var user;
    if (req.method === "POST") {
      user = {
        name: req.body.name,
        email: req.body.email,
        password: req.body.password
      };
      return userBll.register(user, function(err, result) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else {
          return res.redirect('/explore');
        }
      });
    } else {
      return res.render("register");
    }
  };


  /*
      登录
      @param email
      @param password
   */

  exports.login_GET_POST = function(req, res) {
    var user;
    if (req.method === "POST") {
      user = {
        email: req.body.userName,
        password: req.body.pwd
      };
      return userBll.login(user, function(err, result) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else {
          return res.send({
            code: 0,
            message: "登录成功",
            result: result
          });
        }
      });
    }
  };

}).call(this);

//# sourceMappingURL=user.js.map
