// Generated by CoffeeScript 1.8.0
(function() {
  var emailInfo, emailInfoArr, i, logHelper, netEaseMailTransport, nodemailer, path, renderEmail, send, sendEmail, swig;

  nodemailer = require("nodemailer");

  path = require("path");

  logHelper = require("../helper/logHelper");

  swig = require("swig");

  emailInfo = require("./emailInfo.json");


  /*
      render email
   */

  renderEmail = function(user, cb) {
    var name, templatePath;
    templatePath = path.join(__dirname, "../views/email", "invite.html");
    name = user.email.split('@')[0];
    return swig.renderFile(templatePath, {
      name: name
    }, function(err, mailContent) {
      if (err) {
        logHelper.errorLog("render email file:" + err);
      }
      return cb(err, mailContent, user);
    });
  };


  /*
      自己服务器邮件发送端口
   */

  netEaseMailTransport = nodemailer.createTransport({
    host: "www.chetansite.com",
    debug: true
  });

  sendEmail = function(user, mailContent, emailInfoArr, cb) {
    var mailOptions;
    mailOptions = {
      from: '驾考学习 <service@chetansite.com>',
      to: user.email,
      subject: "助车网，驾考学习",
      text: "我们是助车网，一个专注于汽车、驾照考试的问答社区，在这里，你可以提出你学车前，学车时，以至于学车后的问题，可以提出所有与汽车相关的问题,也希望你能回答。",
      html: mailContent
    };
    return netEaseMailTransport.sendMail(mailOptions, function(error, info) {
      if (error) {
        return logHelper.emailLog('send email error: ' + mailOptions.to + '   Message error: ' + error);
      } else {
        logHelper.emailLog('send successful email: ' + mailOptions.to + '   Message sent: ' + info.response);
        if (cb && typeof cb === 'function') {
          return cb(emailInfoArr);
        }
      }
    });
  };

  emailInfoArr = emailInfo.emailArr;


  /*
    发送邮件
   */

  i = 0;

  send = function(emailInfoArr) {
    if (i === emailInfoArr.length) {
      netEaseMailTransport.close();
      logHelper.emailLog('all email send success');
      return true;
    }
    return renderEmail(emailInfoArr[i], function(err, mailContent, user) {
      if (err) {
        return logHelper.errorLog('render email:' + err);
      } else {
        return sendEmail(user, mailContent, emailInfoArr, function(emailInfoArr) {
          i = i + 1;
          return send(emailInfoArr);
        });
      }
    });
  };

  send(emailInfoArr);

}).call(this);

//# sourceMappingURL=email.js.map
