// Generated by CoffeeScript 1.8.0
(function() {
  var dbComment;

  dbComment = require("../Dal/dbComments");


  /*
      添加问题评论
       info:
          qId 问题id
          user 用户内容
          content 评论内容
          replyNum 回复数量
          likeNum 赞数
          addTime 添加时间
   */

  exports.add = function(info, cb) {
    var inf;
    inf = {
      qId: info.qId,
      user: info.user,
      content: info.content,
      replyNum: 0,
      likeNum: 0,
      addTime: new Date()
    };
    return dbComment.add(inf, cb);
  };


  /*
      获取问题所以评论
   */

  exports.getAll = function(qId, cb) {
    return dbComment.getAll(qId, cb);
  };


  /*
      添加评论回复
      info:
          cId 评论id
          user 用户信息
          content 回复内容
          addTime 添加时间
   */

  exports.addReply = function(info, cb) {
    var inf;
    inf = {
      cId: info.cId,
      user: info.user,
      content: info.content,
      addTime: new Date()
    };
    return dbComment.addReply(inf, cb);
  };


  /*
      获取问题所以评论
   */

  exports.getAllReply = function(cId, cb) {
    return dbComment.getAllReply(cId, cb);
  };


  /*
      获取用户回答的问题
   */

  exports.getCommentByUser = function(userId, cb) {
    return dbComment.getCommentByUser(userId, cb);
  };


  /*
      修改回复数量
   */

  exports.changeReplyNum = function(commentId, cb) {
    return dbComment.changeReplyNum(commentId, cb);
  };


  /*
      修改赞数量
   */

  exports.changeLikeNum = function(commentId, cb) {
    return dbComment.changeLikeNum(commentId, cb);
  };

}).call(this);

//# sourceMappingURL=commentsBll.js.map
