// Generated by CoffeeScript 1.8.0
(function() {
  var dbQuestion;

  dbQuestion = require("../Dal/dbQuestion");


  /*
      add question
      info:
          title
          content
          userId
   */

  exports.add = function(info, cb) {
    var inf;
    inf = {
      title: info.title,
      content: info.content,
      user: info.user,
      viewNum: 0,
      resNum: 0,
      updateTime: new Date(),
      addTime: new Date()
    };
    return dbQuestion.add(inf, cb);
  };


  /*
      获取单个问题
      id
   */

  exports.single = function(id, cb) {
    return dbQuestion.single(id, cb);
  };


  /*
  	获取所有问题
   */

  exports.all = function(cb) {
    return dbQuestion.all(cb);
  };


  /*
      获取某个用户提出问题
   */

  exports.getQuestionByUser = function(id, cb) {
    return dbQuestion.getQuestionByUser(id, cb);
  };


  /*
      修改更新时间
   */

  exports.changeUpdateTime = function(qId, cb) {
    return dbQuestion.changeUpdateTime(qId, cb);
  };


  /*
      获取最新问题
   */

  exports.getLastQuestion = function(num, cb) {
    return dbQuestion.getLastQuestion(num, cb);
  };


  /*
      获取最新回答问题
   */

  exports.getLastAnsQuestion = function(num, cb) {
    return dbQuestion.getLastAnsQuestion(num, cb);
  };


  /*
      修改查看数
   */

  exports.changeViewNum = function(qId, cb) {
    return dbQuestion.changeViewNum(qId, cb);
  };


  /*
  	修改回复数
   */

  exports.changeResNum = function(qId, cb) {
    return dbQuestion.changeResNum(qId, cb);
  };

}).call(this);

//# sourceMappingURL=questionBll.js.map
