// Generated by CoffeeScript 1.8.0
(function() {
  var questionBll;

  questionBll = require("../Dal/dbQuestion");


  /*
      add question
      info:
          title
          content
          userId
   */

  exports.add = function(info, cb) {
    var inf;
    inf = {
      title: info.title,
      content: info.content,
      user: info.user,
      viewNum: 0,
      resNum: 0,
      updateTime: new Date(),
      addTime: new Date()
    };
    return questionBll.add(inf, cb);
  };


  /*
      获取单个问题
      id
   */

  exports.single = function(id, cb) {
    return questionBll.single(id, cb);
  };


  /*
  	获取所有问题
   */

  exports.all = function(cb) {
    return questionBll.all(cb);
  };

}).call(this);

//# sourceMappingURL=questionBll.js.map
