// Generated by CoffeeScript 1.8.0
(function() {
  var dbResource;

  dbResource = require("../Dal/dbResource");


  /*
      添加资源
   */

  exports.add = function(info, cb) {
    var inf;
    inf = info;
    inf.addTime = new Date();
    inf.viewNum = 0;
    return dbResource.add(info, cb);
  };


  /*
      获取所有资源
   */

  exports.all = function(cb) {
    return dbResource.all(cb);
  };


  /*
      获取单个资源
   */

  exports.single = function(id, cb) {
    return dbResource.single(id, cb);
  };

}).call(this);

//# sourceMappingURL=resourceBll.js.map
