// Generated by CoffeeScript 1.7.1
(function() {
  var dbUser;

  dbUser = require("../Dal/dbUser");


  /*
      注册
   */

  exports.register = function(user, cb) {
    return dbUser.register(user, cb);
  };


  /*
      登录
   */

  exports.login = function(user, cb) {
    return dbUser.login(user, cb);
  };


  /*
  	获取用户信息
   */

  exports.getUserInfo = function(id, cb) {
    return dbUser.getUserInfo(id, cb);
  };


  /*
      获取所有用户
   */

  exports.getAllUser = function(cb) {
    return dbUser.getAllUser(cb);
  };

}).call(this);

//# sourceMappingURL=userBll.map
