// Generated by CoffeeScript 1.7.1
(function() {
  var dbUser;

  dbUser = require("../Dal/dbUser");


  /*
      注册
   */

  exports.register = function(user, cb) {
    return dbUser.register(user, cb);
  };


  /*
      登录
   */

  exports.login = function(user, cb) {
    return dbUser.login(user, cb);
  };

}).call(this);

//# sourceMappingURL=userBll.map
